services:
  sake-hack-db:
    build: ./postgres
    container_name: sake-hack-db
    restart: always
    volumes:
      - type: volume
        source: sake-hack-db
        target: /var/lib/postgresql/data
      - type: bind
        source: ./postgres/config/default.conf
        target: /etc/postgresql/postgresql.conf
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost -p ${POSTGRES_HOST_PORT}",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - sake_hack_network

  sake-hack-pgweb:
    image: sosedoff/pgweb
    container_name: sake-hack-pgweb
    restart: always
    depends_on:
      sake-hack-db:
        condition: service_healthy
    ports:
      - 8081:8081
    env_file:
      - .env
    environment:
      PGWEB_DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@sake-hack-db:5432/${POSTGRES_DB}?sslmode=disable"
    networks:
      - sake_hack_network

  sake-hack-valkey:
    image: valkey/valkey:9.0.0
    container_name: sake-hack-valkey
    restart: always
    volumes:
      - type: volume
        source: sake-hack-valkey-data
        target: /data
    ports:
      - 6379:6379
    env_file:
      - .env
    command: >
      valkey-server
      --appendonly yes
      --requirepass ${VALKEY_PASSWORD}
    networks:
      - sake_hack_network

volumes:
  sake-hack-db:
  sake-hack-valkey-data:

networks:
  sake_hack_network:
    name: sake_hack_network
    driver: bridge
